### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by lBroth** [kamsteegsoftware/react-native-alternate-icons#1]
android support

**Comment by hawkrives** [comment]
@lBroth (I'm not a maintainer but) do you have any links to the documentation for how the Android platform supports this? For example, iOS' docs live at https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname.

I'm asking because as far as I can tell, the Android operating system just doesn't support this feature at all, so I'm not sure how this _could_ be implemented.

**Comment by lBroth** [comment]
@hawkrives Take a look at:
https://stackoverflow.com/questions/1103027/how-to-change-an-application-icon-programmatically-in-android 

https://github.com/myinnos/AppIconNameChanger

**Comment by hawkrives** [comment]
@lBroth Thank you for those links. I would never have thought of using the ability to remove and add shortcuts programmatically to change the homescreen icon.

Now, again, I am not the maintainer of this package, but reading through that StackOverflow thread, I see several people saying that the method no longer works on Marshmallow (6.0) and above. Given that, and given that people can use launchers that don't even support custom shortcuts at all, and given that that's not a supported feature of Android's standard Launcher API; well, if I was a maintainer of this package, which I'm not, I would be opposed to including that feature in here.

Now. With all that said, I don't know @kamsteegsoftware; they may be happy to review a code contribution that adds this ability on Android. But I wouldn't hold my breath waiting for them to add it themselves.

Have a great day!

**Comment by joeykamsteeg** [comment]
@hawkrives Thanks for your research on this issue! I have only time the next week to implement this issue, so if you would like to implement this feature earlier, go ahead! 😀Send me a pull request on this issue and I will merge it to the master and then I publish a new version to npm.

**Comment by henninghall** [comment]
@PsykoSoldi3r Any update on this? 😃

**Comment by joeykamsteeg** [comment]
Thanks to @TomMahle for implementing the new feature!

I have published a new version to npm under a beta tag.
`npm install react-native-alternate-icons@beta`

**Comment by getnashty** [comment]
@TomMahle @PsykoSoldi3r is this going to make it in?

**Comment by joeykamsteeg** [comment]
I guess we could best wait for official support by Google it self if they are going to implement custom icons on Android. For now I'm going to close this issue
