### ISSUE TITLE
Icon not replaced when some prompts are visible

### ISSUE THREAD

**Issue by henninghall** [kamsteegsoftware/react-native-alternate-icons#4]
Found that the icon won't be replaced when the "Enable location" prompt is visible. This happens first time the app is installed. Might be other prompts that prevents this as well. 

Found a workaround where I am looping until the current icon is the desired one. This interval loop might be better off included in this project itself.

**Comment by ssatyal** [comment]
I'm experiencing the same issue. My current solution is to wait until an input is given from the location services prompt and then execute the app icon logic.
